name: Pulumi preview
on:
  workflow_dispatch:
  
  pull_request:
    branches:
      - main

env:
  PULUMI_STACK_NAME: "dev"

permissions:
  id-token: write        # This is required for requesting the AWS creds
  pull-requests: write   # This is required for comments on pr
  contents: read         # This is required for actions/checkout

jobs:
  preview:
    name: Pulumi preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Preview infrastructure changes
        uses: ./.github/actions/pulumi_command
        with:
          pulumiCommand: preview
          pulumiRefresh: true
          pulumiDiff: true
          pulumiAccessToken: ${{ secrets.PULUMI_ACCESS_TOKEN }}
          pulumiPassphrase: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
          pulumiStackName: ${{ env.PULUMI_STACK_NAME }}